// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _13_school_management_system.Models;

#nullable disable

namespace _13_school_management_system.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260121134042_AddUniqueToTeacher")]
    partial class AddUniqueToTeacher
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_13_school_management_system.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Address = "Hà Nội",
                            DateOfBirth = new DateTime(2002, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentName = "Lê Văn E",
                            TeacherId = 1
                        },
                        new
                        {
                            StudentId = 2,
                            Address = "TP. Hồ Chí Minh",
                            DateOfBirth = new DateTime(2003, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentName = "Phạm Thị F",
                            TeacherId = 1
                        },
                        new
                        {
                            StudentId = 3,
                            Address = "Đà Nẵng",
                            DateOfBirth = new DateTime(2001, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentName = "Hoàng Văn G",
                            TeacherId = 2
                        },
                        new
                        {
                            StudentId = 4,
                            Address = "Cần Thơ",
                            DateOfBirth = new DateTime(2002, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentName = "Nguyễn Thị H",
                            TeacherId = 2
                        },
                        new
                        {
                            StudentId = 5,
                            Address = "Hải Phòng",
                            DateOfBirth = new DateTime(2003, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentName = "Trần Văn I",
                            TeacherId = 3
                        },
                        new
                        {
                            StudentId = 6,
                            Address = "Huế",
                            DateOfBirth = new DateTime(2001, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentName = "Võ Thị K",
                            TeacherId = 3
                        },
                        new
                        {
                            StudentId = 7,
                            Address = "Bình Dương",
                            DateOfBirth = new DateTime(2002, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentName = "Đặng Văn L",
                            TeacherId = 4
                        },
                        new
                        {
                            StudentId = 8,
                            Address = "Đồng Nai",
                            DateOfBirth = new DateTime(2003, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentName = "Bùi Thị M",
                            TeacherId = 4
                        },
                        new
                        {
                            StudentId = 9,
                            Address = "Quảng Nam",
                            DateOfBirth = new DateTime(2002, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentName = "Phan Văn N",
                            TeacherId = 4
                        },
                        new
                        {
                            StudentId = 10,
                            Address = "Nghệ An",
                            DateOfBirth = new DateTime(2001, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentName = "Ngô Thị O",
                            TeacherId = 1
                        });
                });

            modelBuilder.Entity("_13_school_management_system.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherId"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("TeacherId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            TeacherId = 1,
                            Department = "Công nghệ thông tin",
                            Email = "a.nguyen@school.com",
                            TeacherName = "Nguyễn Văn A"
                        },
                        new
                        {
                            TeacherId = 2,
                            Department = "Khoa học máy tính",
                            Email = "b.tran@school.com",
                            TeacherName = "Trần Thị B"
                        },
                        new
                        {
                            TeacherId = 3,
                            Department = "Hệ thống thông tin",
                            Email = "c.le@school.com",
                            TeacherName = "Lê Hoàng C"
                        },
                        new
                        {
                            TeacherId = 4,
                            Department = "Kỹ thuật phần mềm",
                            Email = "d.pham@school.com",
                            TeacherName = "Phạm Minh D"
                        });
                });

            modelBuilder.Entity("_13_school_management_system.Student", b =>
                {
                    b.HasOne("_13_school_management_system.Teacher", "Teacher")
                        .WithMany("Students")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("_13_school_management_system.Teacher", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
