// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _14_library_management_system_practice.Models;

#nullable disable

namespace _14_library_management_system_practice.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_14_library_management_system_practice.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BookId")
                        .IsUnique();

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Robert C. Martin",
                            Availability = "Available",
                            BookId = 1001,
                            ISBN = "9780132350884",
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Robert C. Martin",
                            Availability = "Available",
                            BookId = 1002,
                            ISBN = "9780134494166",
                            Title = "Clean Architecture"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Erich Gamma",
                            Availability = "Borrowed",
                            BookId = 1003,
                            ISBN = "9780201633610",
                            Title = "Design Patterns"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Martin Fowler",
                            Availability = "Available",
                            BookId = 1004,
                            ISBN = "9780201485677",
                            Title = "Refactoring"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Andrew Hunt",
                            Availability = "Borrowed",
                            BookId = 1005,
                            ISBN = "9780201616224",
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Kyle Simpson",
                            Availability = "Available",
                            BookId = 1006,
                            ISBN = "9781491904244",
                            Title = "You Don't Know JS"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Thomas H. Cormen",
                            Availability = "Available",
                            BookId = 1007,
                            ISBN = "9780262033848",
                            Title = "Introduction to Algorithms"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Adam Freeman",
                            Availability = "Borrowed",
                            BookId = 1008,
                            ISBN = "9781484254394",
                            Title = "ASP.NET Core MVC"
                        });
                });

            modelBuilder.Entity("_14_library_management_system_practice.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Password = "admin123",
                            Role = "admin",
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            Password = "guest123",
                            Role = "guest",
                            Username = "guest1"
                        },
                        new
                        {
                            UserId = 3,
                            Password = "guest123",
                            Role = "guest",
                            Username = "guest2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
