// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _13_school_management_system_practice.Models;

#nullable disable

namespace _13_school_management_system_practice.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_13_school_management_system_practice.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Nguyễn Trãi, Quận 5, TP.HCM",
                            DateOfBirth = new DateTime(2002, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentName = "Phạm Minh Hoàng",
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "45 Lê Lợi, Quận 1, TP.HCM",
                            DateOfBirth = new DateTime(2003, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentName = "Nguyễn Thị Lan",
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 3,
                            Address = "78 Hai Bà Trưng, Hà Nội",
                            DateOfBirth = new DateTime(2001, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentName = "Trần Quốc Khánh",
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 4,
                            Address = "12 Trường Chinh, Đà Nẵng",
                            DateOfBirth = new DateTime(2002, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentName = "Lê Thị Hồng",
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 5,
                            Address = "90 Nguyễn Huệ, Huế",
                            DateOfBirth = new DateTime(2003, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentName = "Võ Minh Tuấn",
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 6,
                            Address = "66 Lý Thường Kiệt, TP.HCM",
                            DateOfBirth = new DateTime(2001, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentName = "Phan Thanh Tùng",
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 7,
                            Address = "34 Pasteur, TP.HCM",
                            DateOfBirth = new DateTime(2002, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentName = "Đặng Ngọc Mai",
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 8,
                            Address = "101 Cách Mạng Tháng 8, Cần Thơ",
                            DateOfBirth = new DateTime(2003, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentName = "Bùi Quốc Dũng",
                            TeacherId = 3
                        });
                });

            modelBuilder.Entity("_13_school_management_system_practice.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "Công nghệ thông tin",
                            Email = "nguyenvana@school.com",
                            TeacherName = "Nguyễn Văn A"
                        },
                        new
                        {
                            Id = 2,
                            Department = "Toán học",
                            Email = "tranthib@school.com",
                            TeacherName = "Trần Thị B"
                        },
                        new
                        {
                            Id = 3,
                            Department = "Vật lý",
                            Email = "levanc@school.com",
                            TeacherName = "Lê Văn C"
                        });
                });

            modelBuilder.Entity("_13_school_management_system_practice.Models.Student", b =>
                {
                    b.HasOne("_13_school_management_system_practice.Models.Teacher", "Teacher")
                        .WithMany("Students")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("_13_school_management_system_practice.Models.Teacher", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
